spring:
  h2.console:
      enabled: false
      path: '/dbconsole'
  datasource:
    username: 'admin'
    password: 'admin'
    url: 'jdbc:h2:file:/home/marcin/Projects/organizationApp/testApp-db'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    baseline-on-migrate: true
#actuator
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
#keycloak
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'OrganizationApp'
  resource: 'app-spring-client'
  public-client: true